# Generated by Django 3.0.3 on 2020-03-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextScraperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.TextField(blank=True)),
                ('request_sent_datetime', models.DateTimeField(auto_now_add=True)),
                ('request_done_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('error', 'error'), ('processing', 'processing'), ('done', 'done')], default='processing', max_length=10)),
            ],
        ),
    ]
