# Generated by Django 3.0.3 on 2020-03-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('error', 'error'), ('processing', 'processing'), ('done', 'done')], default='processing', max_length=10)),
                ('request_sent_datetime', models.DateTimeField(auto_now_add=True)),
                ('request_done_datetime', models.DateTimeField(blank=True, null=True)),
                ('scrapping', models.CharField(choices=[('text', 'text'), ('images', 'images')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='textscrapermodel',
            name='request_done_datetime',
        ),
        migrations.RemoveField(
            model_name='textscrapermodel',
            name='request_sent_datetime',
        ),
        migrations.RemoveField(
            model_name='textscrapermodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='textscrapermodel',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ImageScraperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pic/folder/None/no-img.jpg', upload_to='images/')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_scraper', to='scraper.URLModel')),
            ],
        ),
        migrations.AlterField(
            model_name='textscrapermodel',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_scraper', to='scraper.URLModel'),
        ),
    ]
