# Generated by Django 3.0.3 on 2020-03-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200301_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='url',
            new_name='url_address',
        ),
    ]
