# Generated by Django 3.0.3 on 2020-03-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200301_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='url_address',
            new_name='request_url',
        ),
    ]
