# Generated by Django 3.0.3 on 2020-03-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200301_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='request_url',
            new_name='website_url',
        ),
    ]
